### ISSUE TITLE
Two 2D pipeline runs failed in Prod - 12/19/2023

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#413]
This issue was reported by Bryan H,

The pipeline runs:
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/8c095892-ac26-4099-9779-377022309d76?schematic
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/8c095892-ac26-4099-9779-377022309d76

It seems that after these failed runs, the user reran this pipeline, and the run completed successfully. 
Please investigate.

**Comment by philipmac** [comment]
Disk quota exceeded: '/gs1/Scratch'
```
Filesystem    Size  Used Avail Use% Mounted on
/gs1              3.6P  2.6P  1.1P  72% /gs1
```
if the filesystem is claiming its quota is exceeded one time in the past three months during which two runs were submitted. This issue was then resolved within HPC, and subsequent runs work. 
There is nothing we can do about this, although I can mention it to HPC admins.
